repos:
  # Basic checks
  # TODO: Add test file checking
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ex=md]
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
