services:
  eduspec:
    image: eduspec
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 0s
    environment:
      - DATA_DIR=/data
    volumes:
      - data:/data:rw
    build:
      context: .
      dockerfile: ./Dockerfile

    ports:
      - 8501:8501

  eduspec-editor:
    extends:
      service: eduspec
    environment:
      - MAIN_FILE=editornavigation.py
      - PORT=8502
    ports: !override
      - 8502:8502

volumes:
  data:
