name: Ruff linter

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v6

      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Ruff
        run:
          pip install ruff

      - name: Run Ruff linter
        run:
          ruff check --color always
